name: Update File List

on:
  push:
    branches:
      - main  # 选择你要测试的分支

jobs:
  update-file-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1  # 仅克隆最新的提交

    - name: Initialize file list
      run: echo "[]" > file_list.json

    - name: List all files in stages
      run: |
        find . -type d -not -path './.git*' -print0 | while IFS= read -r -d '' dir; do
          find "$dir" -maxdepth 1 -type f -not -path './.git/*' -print0 | xargs -0 -I {} echo "\"{}\"" > tmp_file_list.txt
          if [ -s tmp_file_list.txt ]; then
            jq -s add file_list.json tmp_file_list.txt > tmp_combined_list.json
            mv tmp_combined_list.json file_list.json
          fi
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add file_list.json
        git commit -m 'Update file list'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
